version: '3.1'
services:
  mongo:
    image: mongo:5.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:password
    ports:
      - 27017:27017
    volumes:
      - ./docker/volumes/mongo/data/db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  mongo-express:
    image: mongo-express:0.54.0
    # NOTE MongoDB has a slow startup time!
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 9091:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN:true
      - ME_CONFIG_MONGODB_ADMINUSERNAME:root
      - ME_CONFIG_MONGODB_ADMINPASSWORD:password
      - ME_CONFIG_MONGODB_URL:mongodb://mongo:27017/