version: '3.1'
services:
  mongo:
    image: mongo:5.0
    # restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME:mariotoilet
      - MONGO_INITDB_ROOT_PASSWORD:luigismansion
    volumes:
      - ./docker/volumes/mongo/data/db:/data/db  
  mongo-express:
    image: mongo-express:0.54.0
    # NOTE MongoDB has a slow startup time!
    # restart: always
    ports:
      - 9091:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN:true
      - ME_CONFIG_MONGODB_ADMINUSERNAME:mariotoilet
      - ME_CONFIG_MONGODB_ADMINPASSWORD:luigismansion
      - ME_CONFIG_MONGODB_URL:mongodb://mariotoilet:luigismansion@mongo:27017/
